const genres = {
  Action: 20,
  Adventure: 19,
  Comedy: 18,
  Drama: 17,
  Fantasy: 16,
  Horror: 15,
  Mystery: 14,
  Romance: 13,
  "Science Fiction": 12,
  Thriller: 11,
  Documentary: 10,
  Animation: 9,
  Crime: 8,
  Family: 7,
  History: 6,
  Music: 5,
  Sport: 4,
  War: 3,
  Western: 2,
  Biography: 1,
};
const moods = {
  Uplifting: 20,
  Adventurous: 19,
  Humorous: 18,
  Dramatic: 17,
  Fantastical: 16,
  Chilling: 15,
  Mysterious: 14,
  Romantic: 13,
  Futuristic: 12,
  Suspenseful: 11,
  Informative: 10,
  Imaginative: 9,
  "Crime-solving": 8,
  Heartwarming: 7,
  Historical: 6,
  Musical: 5,
  Energetic: 4,
  Intense: 3,
  "Western-themed": 2,
  Inspirational: 1,
};

module.exports = {
  genres,
  moods,
};
